stages:
  - build
  - package
  - deploy
  - auto_merge
build:
  image: yeyudekuangxiang/golang:1.17-alpine3.16
  stage: build
  tags:
    - docker
  only:
    - tags
  before_script:
    - eval $(ssh-agent -s)
    - echo $SSH_PRIVATE_KEY
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\\n\\tStrictHostKeyChecking no\\n\\n" > ~/.ssh/config'
  script:
    - go env
    - sh ./scripts/build.sh mp2c
  artifacts:
    paths:
      - ./cmd/mp2c/mp2c
package:
  stage: package
  tags:
    - docker
  only:
    - tags
  dependencies:
    - build
  script:
    - docker version
    - sh ./scripts/package.sh mp2c

deploy-prod:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  when: manual
  environment:
    name: production
    url: https://go-api.miotech.com
  tags:
    - k8s
  only:
    - tags
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c