stages:
  - build
  - package
  - deploy
  - auto_merge
build:
  image: golang:1.17
  stage: build
  only:
    - develop
    - master
    - tags
    - /^hotfix-.+$/
    - /^feature-.+$/
  script:
    - sh ./scripts/build.sh mp2c
  artifacts:
    paths:
      - ./cmd/mp2c/mp2c
package:
  stage: package
  only:
    - develop
    - master
    - tags
    - /^hotfix-.+$/
    - /^feature-.+$/
  dependencies:
    - build
  script:
    - sh ./scripts/package.sh mp2c


deploy-dev:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: develop
    url: https://godev-api.miotech.com
  tags:
    - k8s
  only:
    - develop
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-prod:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: production
    url: https://go-api.miotech.com
  tags:
    - k8s
  only:
    - tags
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-feature:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://godev-api.miotech.com/$CI_COMMIT_REF_SLUG/
    on_stop: stop-deploy-dev
  tags:
    - k8s
  only:
    - /^feature-.+$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-pre-prod:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: pre-prod
    url: https://go-api.miotech.com/pre-prod/
  tags:
    - k8s
  only:
    - master
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-hotfix:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    on_stop: stop-deploy-prod
  tags:
    - k8s
  only:
    - /^hotfix-.+$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

stop-deploy-prod:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  variables:
    GIT_STRATEGY: none
    RELEASE_NAME: "mp2c-go${CI_COMMIT_REF_NAME}"
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  tags:
    - k8s
  when: manual
  only:
    - /^hotfix-.+$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    -  helm uninstall $RELEASE_NAME  -n prod

stop-deploy-dev:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  variables:
    GIT_STRATEGY: none
    RELEASE_NAME: "mp2c-go${CI_COMMIT_REF_NAME}"
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  tags:
    - k8s
  when: manual
  only:
    - /^feature-.+$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    -  helm uninstall $RELEASE_NAME -n dev

auto_merge:
  image: golang:1.17
  stage: auto_merge
  rules:
    - if: "$CI_PIPELINE_SOURCE ==  'merge_request_event' && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(release-|hotfix-).+$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'"
      when: always
  script:
    - go run cmd/command/main.go gitlab merge auto $CI_MERGE_REQUEST_PROJECT_ID $CI_MERGE_REQUEST_IID $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME