stages:
  - build
  - package
  - deploy
  - auto_merge
build:
  image: yeyudekuangxiang/golang:1.17-alpine3.16
  stage: build
  tags:
    - build
  only:
    - develop
    - master
    - tags
  cache:
    key:
      files:
        - go.mod
        - go.sum
      prefix: mp2c-go-cache
    paths:
      - .cache
  before_script:
    - echo $SSH_PRIVATE_KEY
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\\n\\tStrictHostKeyChecking no\\n\\n" > ~/.ssh/config'
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
    - go env
    - sh ./scripts/build.sh mp2c
  artifacts:
    paths:
      - ./cmd/mp2c/mp2c

build-manual:
  image: yeyudekuangxiang/golang:1.17-alpine3.16
  stage: build
  allow_failure: false
  tags:
    - build
  when: manual
  only:
    - /^hotfix-.+$/
    - /^feature-.+$/
  cache:
    key:
      files:
        - go.mod
        - go.sum
      prefix: mp2c-go-cache
    paths:
      - .cache
  before_script:
    - echo $SSH_PRIVATE_KEY
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\\n\\tStrictHostKeyChecking no\\n\\n" > ~/.ssh/config'
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
    - go env
    - sh ./scripts/build.sh mp2c
  artifacts:
    paths:
      - ./cmd/mp2c/mp2c
package:
  stage: package
  tags:
    - docker
  only:
    - develop
    - master
    - tags
  dependencies:
    - build
  script:
    - sh ./scripts/package.sh mp2c

package-manual:
  stage: package
  when: on_success
  tags:
    - docker
  only:
    - /^hotfix-.+$/
    - /^feature-.+$/
  dependencies:
    - build-manual
  script:
    - sh ./scripts/package.sh mp2c

deploy-dev:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: develop
    url: https://godev-api.miotech.com
  tags:
    - k8s
  only:
    - develop
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-prod:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: production
    url: https://go-api.miotech.com
  tags:
    - k8s
  only:
    - tags
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-feature:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://godev-api.miotech.com/$CI_COMMIT_REF_SLUG/
    on_stop: stop-deploy-feature
    auto_stop_in: 7 days
  when: on_success
  tags:
    - k8s
  only:
    - /^feature-.+$/
  before_script:
    - env
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-pre-prod:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: pre-prod
    url: https://go-api.miotech.com/pre-prod/
  tags:
    - k8s
  only:
    - master
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-hotfix:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://go-api.miotech.com/$CI_COMMIT_REF_SLUG/
    on_stop: stop-deploy-hotfix
    auto_stop_in: 7 days
  tags:
    - k8s
  when: on_success
  only:
    - /^hotfix-.+$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

stop-deploy-hotfix:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  variables:
    GIT_STRATEGY: none
    RELEASE_NAME: "mp2c-go${CI_COMMIT_REF_NAME}"
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  tags:
    - k8s
  when: manual
  only:
    - /^hotfix-.+$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    -  helm uninstall $RELEASE_NAME  -n prod

stop-deploy-feature:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  variables:
    GIT_STRATEGY: none
    RELEASE_NAME: "mp2c-go${CI_COMMIT_REF_NAME}"
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  tags:
    - k8s
  when: manual
  only:
    - /^feature-.+$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    -  helm uninstall $RELEASE_NAME -n dev