stages:
  - build
  - package
  - deploy
build:
  image: golang:1.14
  stage: build
  only:
    - develop
    - tags
  script:
    - env GOPROXY=https://goproxy.cn,https://goproxy.io,direct CGO_ENABLED=0 GOOS=linux GOARCH=amd64  go build .
  artifacts:
    paths:
      - mio
package:
  stage: package
  only:
    - develop
    - tags
  dependencies:
    - build
  script:
    - export IMAGE_TAG=${CI_BUILD_DOCKER_URL}mioyingtech/mio:$CI_COMMIT_REF_NAME
    - docker login -u $CI_BUILD_DOCKER_USER -p $CI_BUILD_TOKEN $CI_BUILD_DOCKER_URL
    - docker build -t $IMAGE_TAG -f ./build/Dockerfile .
    - docker push $IMAGE_TAG
deploy:
  image:
    name: bitnami/kubectl:1.20.10
    entrypoint: [""]
  stage: deploy
  only:
    - develop
    - tags
  before_script:
    - echo ${k8s_config} | base64 -d >> ./config-ali
    - export KUBECONFIG=$(pwd)/config-ali
  script:
    - bash ./build/deploy.sh $CI_COMMIT_REF_NAME