stages:
  - build
  - package
  - deploy
build:
  image: golang:1.17
  stage: build
  only:
    - develop
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^feature-.*$/
  script:
    - sh ./scripts/build.sh mp2c
  artifacts:
    paths:
      - ./cmd/mp2c/mp2c
package:
  stage: package
  only:
    - develop
    - tags
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^feature-.*$/
  dependencies:
    - build
  script:
    - sh ./scripts/package.sh mp2c


deploy-dev:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: develop
    url: https://godev-api.miotech.com
  tags:
    - k8s
  only:
    - develop
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-prod:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: production
    url: https://go-api.miotech.com
  tags:
    - k8s
  only:
    - tags
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-feature:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://godev-api.miotech.com/$CI_COMMIT_REF_NAME/
  tags:
    - k8s
  only:
    - /^feature-.*$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-release:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://go-api.miotech.com/$CI_COMMIT_REF_NAME/
  tags:
    - k8s
  only:
    - /^release-.*$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c

deploy-hotfix:
  image: yeyudekuangxiang/helm:3.8.1
  stage: deploy
  tags:
    - k8s
  only:
    - /^hotfix-.*$/
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $kube_config_sh | base64 -d > $HOME/.kube/config
  script:
    - sh ./scripts/deploy.sh mp2c