// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"{{if .hasTimeout}}
	"time"{{end}}
    {{if .hasJwtMiddleware}}"{{.projectPath}}/{{.jwtMiddlewarePath}}"{{end}}
	{{.importPackages}}
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{{.routesAdditions}}
}
